version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        PROJECT_VERSION: ${PROJECT_VERSION}
        JVM_OPTS: ${JVM_OPTS}
    ports:
      - "8081:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - app-binary:/app/data

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
  app-binary:
