spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
        default_batch_fetch_size: 10 # Pagination -> postgreSQL에서는 IN이 아닌 ANY로
    open-in-view: false
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 5MB
jwt:
  issuer: demo-api
  access-token:
    validity-seconds: 900  # 15분
  refresh-token:
    validity-seconds: 2592000  # 30일
  secret: ${JWT_SECRET:dev-secret-key-must-be-at-least-32-characters-long}

logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE
    com.example.jwt: DEBUG
