server:
  port: 80

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 10 # Pagination -> postgreSQL에서는 IN이 아닌 ANY로
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 5MB

logging:
  level:
    root: info