spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
          - "loggers"
  endpoint:
    health:
      show-details: "ALWAYS"
